[workspace]
members = ["crates/cli", "crates/sources", "crates/k8s"]

[workspace.package]
authors = ["Max HÃ¶sel <github@maxhoesel.de>"]
license-file = "LICENSE"
description = "Keep MetalLB updated with a dynamic Ipv6 prefix"
version = "0.1.0"
