[workspace]
members = ["crates/cli", "crates/sources", "crates/k8s"]
resolver = "2"

[workspace.package]
authors = ["Max HÃ¶sel <github@maxhoesel.de>"]
license-file = "LICENSE"
description = "Keep MetalLB updated with a dynamic Ipv6 prefix"
version = "6.0.1"
