apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metallb-dyn6.fullname" . }}
  labels:
    {{- include "metallb-dyn6.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "metallb-dyn6.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "metallb-dyn6.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "metallb-dyn6.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: RUST_LOG
              value: {{ .Values.loglevel | quote }}
            - name: METALLB_DYN6_HOST_RANGE
              value: {{ .Values.metallb.hostRange | quote }}
            - name: METALLB_DYN6_METALLB_POOL
              value: {{ .Values.metallb.pool | quote }}
            - name: METALLB_DYN6_SOURCE
              value: {{ .Values.dyn6.source | quote }}
            {{- if .Values.dyn6.subnetOverride.enabled }}
            - name: METALLB_DYN6_SUBNET_OVERRIDE
              value: {{ .Values.dyn6.subnetOverride.override | quote }}
            - name: METALLB_DYN6_PREFIX_LENGTH
              value: {{ .Values.dyn6.subnetOverride.prefixLength | quote }}
            {{- end }}
            - name: METALLB_DYN6_UPDATE_INTERVAL
              value: {{ .Values.dyn6.updateInterval | quote }}
            - name: METALLB_DYN6_METALLB_NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: METALLB_DYN6_METALLB_LABEL_SELECTOR
              value: {{ .Values.metallb.podsLabelSelector | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
